### ISSUE TITLE
it is expanded when scrolling up, I cannot controll this behavior

### ISSUE THREAD

**Issue by changgyu-brandi** [germainkevinbusiness/CollapsingTopBarCompose#1]
Hi, I'm using your library in my project.
adopting collapsingToolbar, I realized that the toolbar is always opened when scrolling up.
I want to open the toolbar when scrolling to top.
Is there any way for this?

**Comment by germainkevinbusiness** [comment]
Hello, can you please rephrase your question, I do not understand your statement, thanks in advance, and also can you please show a screenshot of the problem you are facing as well

**Comment by changgyu-brandi** [comment]
What I want to is like `app:layout_scrollFlags="scroll|exitUntilCollapsed"` feature that exists in xml. In your library, the expandedHeight is always opened when scrolling up. Fortunately, I customized your library and it solved my problem. Thanks for your concern.

**Comment by germainkevinbusiness** [comment]
Glad you solved the issue !
