### ISSUE TITLE
Other than showing the background color on the TopAppbar when it is expanded, can I show an Image?

### ISSUE THREAD

**Issue by joelkanyi** [germainkevinbusiness/CollapsingTopBarCompose#2]
Also I remove the title and subtitle when it is expanded?

**Comment by germainkevinbusiness** [comment]
Yes you can show an image! When the CollapsingTopBar is expanded, you can display any composable inside the expandedTitle slot and the subtitle slot, which means even if you want to pass an image composable that fits the size of the CollapsingTopBar, you can also do that but only when the CollapsingTopBar is expanded

**Comment by germainkevinbusiness** [comment]
> Also I remove the title and subtitle when it is expanded?

Yes, by simply passing nothing to the title/expandedTitle and subtitle slot, the CollapsingTopBar will draw normally, just without them

**Comment by joelkanyi** [comment]
Cool thanks
